### ISSUE TITLE
Implement với Axios

### ISSUE THREAD

**Issue by vietvh-3042** [hunghg255/reactjs-handle-refresh-token#2]
Mình đang implement với Axios mong tác giả support mình viết như này có vấn đề gì không:

```
const authAxiosInstance = axios.create({
  baseURL: import.meta.env.VITE_BASE_API_URL,
  headers: { 'Content-Type': 'application/json' },
});

authAxiosInstance.interceptors.response.use(async (configs) => {
  const token = (await tokenManager.getToken()) as string;
  return injectBearer(token, configs);
});

export default authAxiosInstance;

```

**Comment by hunghg255** [comment]
@vietvh-3042 xử lý theo interceptors thì phải làm theo cách `interceptors ` chứ, như này vẫn có lỗi, cái này là gọi xong có lỗi thì nó mới chui vào cái response này,.

còn cái token manager là mình xử lý trước cả khi call api rồi

**Comment by vietvh-3042** [comment]
> @vietvh-3042 xử lý theo interceptors thì phải làm theo cách `interceptors ` chứ, như này vẫn có lỗi, cái này là gọi xong có lỗi thì nó mới chui vào cái response này,.
> 
> còn cái token manager là mình xử lý trước cả khi call api rồi

@hunghg255  Thế chỗ này mình phải làm như nào cho đúng nhỉ, có thể cho mình xin example được không, mình thấy có example với umi-reques mà hiện tại mình đang sử dụng axios

**Comment by hunghg255** [comment]
file này mình đã viết xử lý theo interceptors https://github.com/hunghg255/reactjs-handle-refresh-token/blob/master/src/apis/axios/request.ts
bạn thay cái api refresh token vào thôi

> > @vietvh-3042 xử lý theo interceptors thì phải làm theo cách `interceptors ` chứ, như này vẫn có lỗi, cái này là gọi xong có lỗi thì nó mới chui vào cái response này,.
> > còn cái token manager là mình xử lý trước cả khi call api rồi
> 
> @hunghg255 Thế chỗ này mình phải làm như nào cho đúng nhỉ, có thể cho mình xin example được không, mình thấy có example với umi-reques mà hiện tại mình đang sử dụng axios
